import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from '@/hooks/use-toast';

export interface QuoteItem {
  product_id: string;
  product_name: string;
  product_sku?: string;
  quantity: number;
  unit_price?: number;
  total_price?: number;
  notes?: string;
}

export interface Quote {
  id: string;
  quote_number: string;
  customer_name: string;
  customer_email: string;
  customer_phone?: string;
  company_name?: string;
  status: 'pending' | 'reviewed' | 'approved' | 'rejected' | 'converted';
  subtotal: number;
  discount_amount: number;
  tax_amount: number;
  total_amount: number;
  notes?: string;
  admin_notes?: string;
  valid_until?: string;
  created_at: string;
  updated_at: string;
  items?: QuoteItem[];
}

export const useQuotes = () => {
  const { user } = useAuth();
  const queryClient = useQueryClient();

  const { data: quotes, isLoading } = useQuery({
    queryKey: ['quotes', user?.id],
    queryFn: async () => {
      if (!user) return [];
      
      const { data, error } = await supabase
        .from('quotes')
        .select(`
          *,
          items:quote_items(*)
        `)
        .eq('user_id', user.id)
        .order('created_at', { ascending: false });

      if (error) throw error;
      return data as Quote[];
    },
    enabled: !!user,
  });

  const createQuoteMutation = useMutation({
    mutationFn: async (quoteData: {
      items: QuoteItem[];
      customer_name: string;
      customer_email: string;
      customer_phone?: string;
      company_name?: string;
      notes?: string;
    }) => {
      if (!user) throw new Error('User must be logged in');

      // Calculate totals
      const subtotal = quoteData.items.reduce((sum, item) => sum + (item.quantity * (item.unit_price || 0)), 0);
      
      // Create quote
      const { data: quote, error: quoteError } = await supabase
        .from('quotes')
        .insert({
          user_id: user.id,
          customer_name: quoteData.customer_name,
          customer_email: quoteData.customer_email,
          customer_phone: quoteData.customer_phone,
          company_name: quoteData.company_name,
          notes: quoteData.notes,
          subtotal,
          total_amount: subtotal,
          quote_number: '', // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (quoteError) throw quoteError;

      // Create quote items
      const { error: itemsError } = await supabase
        .from('quote_items')
        .insert(
          quoteData.items.map(item => ({
            quote_id: quote.id,
            product_id: item.product_id,
            product_name: item.product_name,
            product_sku: item.product_sku,
            quantity: item.quantity,
            unit_price: item.unit_price || 0,
            total_price: (item.unit_price || 0) * item.quantity,
            notes: item.notes,
          }))
        );

      if (itemsError) throw itemsError;

      return quote;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['quotes'] });
      toast({
        title: "Quote Requested",
        description: "Your quote request has been submitted successfully.",
      });
    },
    onError: (error) => {
      console.error('Error creating quote:', error);
      toast({
        title: "Error",
        description: "Failed to create quote request. Please try again.",
        variant: "destructive",
      });
    },
  });

  return {
    quotes,
    isLoading,
    createQuote: createQuoteMutation.mutate,
    isCreating: createQuoteMutation.isPending,
  };
};
