// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhsmpefnabqmeteyvtle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoc21wZWZuYWJxbWV0ZXl2dGxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NjkyNjksImV4cCI6MjA1OTI0NTI2OX0.RuKXawpekBEU0KwOIn2O2H9qmZ2TMPmZkcMjTHdculk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);